#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111109 \
    d26a96d2bbf78dcb4b5b43bf95137731ad0db286
git -C rust-s20111109 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20111109/src/libuv
mkdir rust-s20111109/dl
cp rust-s20111031/$(< rust-s20111031/snap.txt) rust-s20111109/dl
cat > rust-s20111109/src/snapshots.txt <<EOF
S 2011-10-31 bd33951
  linux-i386 $(cut -c 43-82 rust-s20111031/snap.txt)
EOF
cd rust-s20111109
patch -p1 <<'EOF'
--- a/configure
+++ b/configure
@@ -411 +411 @@
-if [ $NEED_INIT ]
+if false
@@ -417 +417 @@
-if [ $NEED_UPDATE ]
+if false
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -204 +204 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --llvm-root="$base"/llvm-3.1svn-1/Release+Asserts
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
