#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130623 \
    f82756180bec5a8405e1fc6ee1b22949db24861f
git -C rust-s20130623 config --worktree core.abbrev 7
git -C libuv archive v0.11.5 | tar -xf - -C rust-s20130623/src/libuv
install -Dt rust-s20130623/dl rust-s20130621/$(< rust-s20130621/snap.txt)
cat > rust-s20130623/src/snapshots.txt <<EOF
S 2013-06-21 6759ce4
  linux-x86_64 $(cut -c 45-84 rust-s20130621/snap.txt)
EOF
cd rust-s20130623
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
patch -p1 <<EOF
--- a/src/libextra/terminfo/searcher.rs
+++ b/src/libextra/terminfo/searcher.rs
@@ -51 +50,0 @@
-                    dirs_to_search.push(path("/lib/terminfo"));
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.3svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
