#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110809 \
    e5533a5d5e589bad751e4af3f29dc4c65cb8958e
git -C rust-s20110809 config --worktree core.abbrev 7
mkdir rust-s20110809/dl
cp rust-s20110802/$(< rust-s20110802/snap.txt) rust-s20110809/dl
cat > rust-s20110809/src/snapshots.txt <<EOF
S 2011-08-02 $(cut -f 6 -d - rust-s20110802/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110802/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20110809
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -156 +156 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -563 +563 @@
-        [stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        [stage, glu, "-m32", "-o", saved_out_filename,
@@ -619,0 +620 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.cpp
+++ b/src/rt/rust_shape.cpp
@@ -913 +913 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -211 +211 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-5/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
