#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110802 \
    091a2c2f71c693cc90c5bfb44b18a8092dba4af4
git -C rust-s20110802 config --worktree core.abbrev 7
mkdir rust-s20110802/dl
cp rust-s20110729/$(< rust-s20110729/snap.txt) rust-s20110802/dl
cat > rust-s20110802/src/snapshots.txt <<EOF
S 2011-07-29 5adf87a
  linux-i386 $(cut -c 43-82 rust-s20110729/snap.txt)
EOF
cd rust-s20110802
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -151 +151 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -96 +96 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -559 +559 @@
-        [stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        [stage, glu, "-m32", "-o", saved_out_filename,
@@ -615,0 +616 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -211 +211 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-5/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
