#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110714 \
    7376e751aeed046c29ff4b892b359002de145d2d
git -C rust-s20110714 config --worktree core.abbrev 7
mkdir rust-s20110714/dl
cp rust-s20110711-2/$(< rust-s20110711-2/snap.txt) rust-s20110714/dl
cat > rust-s20110714/src/snapshots.txt <<EOF
S 2011-07-11 a84310a
  linux-i386 $(cut -c 43-82 rust-s20110711-2/snap.txt)
EOF
patch -d rust-s20110714 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -148 +148 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110714 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -97 +97 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-s20110714 -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -495 +495 @@
-        [stage, "-Lrt", "-lrustrt", glu,  "-m32", "-o",
+        [stage, glu,  "-m32", "-o",
@@ -555,0 +556 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -d rust-s20110714 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -209 +209 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-s20110714
PATH="$base"/llvm-3.0svn-4/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110714 -j8 stage2/lib/libstd.rlib stage2/lib/libstd.so
(cd rust-s20110714; CFG_SRC_DIR=. src/etc/make-snapshot.py stage2 > snap.txt)
printf '\a'
