#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110615-2 \
    92bd35075bafc2835cc7dd1075f29e246c0c7c1c
git -C rust-s20110615-2 config --worktree core.abbrev 7
mkdir rust-s20110615-2/dl
cp rust-s20110615-1/$(< rust-s20110615-1/snap.txt) rust-s20110615-2/dl
cat > rust-s20110615-2/src/snapshots.txt <<EOF
S 2011-06-15 01ea27b
  linux-i386 $(cut -c 43-82 rust-s20110615-1/snap.txt)
EOF
patch -d rust-s20110615-2 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110615-2 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -96 +96 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-s20110615-2 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -201 +201 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-s20110615-2
PATH="$base"/llvm-3.0svn-3/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110615-2 -j8 stage1/rustc
(cd rust-s20110615-2; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
