#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130227 \
    a6d9689399d091c3265f00434a69c551a61c28dc
git -C rust-s20130227 config --worktree core.abbrev 7
git -C libuv archive v0.11.5 | tar -xf - -C rust-s20130227/src/libuv
cd rust-s20130227
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -497 +497 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -275 +275 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -g
+  CFG_GCCISH_CFLAGS += -Wall -g
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130204/x86_64-unknown-linux-gnu/stage2 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
