#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110830 \
    be2ad97a610a46a33ee3a32f1e5302c9f41d94a4
git -C rust-s20110830 config --worktree core.abbrev 7
mkdir rust-s20110830/dl
cp rust-s20110829/$(< rust-s20110829/snap.txt) rust-s20110830/dl
cat > rust-s20110830/src/snapshots.txt <<EOF
S 2011-08-29 c9c5ee2
  linux-i386 $(cut -c 43-82 rust-s20110829/snap.txt)
EOF
cd rust-s20110830
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -163 +163 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -578 +578 @@
-         ~"-Lrt", ~"-lrustrt", glu,
+         glu,
@@ -635,0 +636 @@
+    gcc_args += [~"-Lrt", ~"-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_crate_cache.cpp
+++ b/src/rt/rust_crate_cache.cpp
@@ -2 +1,0 @@
-#include "rust_internal.h"
@@ -3,0 +3,2 @@
+#include "rust_internal.h"
+#undef max
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -89,0 +90 @@
+#define alignof rust_alignof
@@ -831 +832 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
