#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120630 \
    ed834f062901d9db56f2430ad292d37c9e5c1812
git -C rust-s20120630 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120630/src/libuv
install -Dt rust-s20120630/dl rust-s20120628-2/$(< rust-s20120628-2/snap.txt)
cat > rust-s20120630/src/snapshots.txt <<EOF
S 2012-06-28 7aa43b2
  linux-x86_64 $(cut -c 45-84 rust-s20120628-2/snap.txt)
EOF
cd rust-s20120630
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -245 +245 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -665 +665 @@
-    explicit ptr(uint8_t *in_p) : p(in_p) {}
+    ptr(uint8_t *in_p) : p(in_p) {}
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
