#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130517 \
    2d28d645422c1617be58c8ca7ad9a457264ca850
git -C rust-s20130517 config --worktree core.abbrev 7
git -C libuv archive v0.11.5 | tar -xf - -C rust-s20130517/src/libuv
cd rust-s20130517
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -122 +122 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130503/x86_64-unknown-linux-gnu/stage1 \
    --llvm-root="$base"/llvm-3.3svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
