#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120602 \
    77c470d183472b357737b6d3e6c7cafc26174c91
git -C rust-s20120602 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120602/src/libuv
install -Dt rust-s20120602/dl rust-s20120530-2/$(< rust-s20120530-2/snap.txt)
cat > rust-s20120602/src/snapshots.txt <<EOF
S 2012-05-30 0c0818b
  linux-x86_64 $(cut -c 45-84 rust-s20120530-2/snap.txt)
EOF
cd rust-s20120602
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
