#!/bin/bash
base=$(pwd)
# sudo apt-get install -y curl
git -C rust worktree add "$base"/rust-s20110505 \
    157f61f8c871e0fd63a57fe63821360d0a0d95fe
git -C rust-s20110505 config --worktree core.abbrev 7
mkdir rust-s20110505/dl
cp rust-s20110503/$(< rust-s20110503/snap.txt) rust-s20110505/dl
cat > rust-s20110505/src/snapshots.txt <<EOF
S 2011-05-03 54bfe8e
  linux-i386 $(cut -c 43-82 rust-s20110503/snap.txt)
EOF
base64 -d <<EOF | zcat | patch -d rust-s20110505 -p1
H4sIAAAAAAAAA52OOwvCQBCEa/MrtkiR41yDWKQSTs8kxCcaxTJEPTXkyXmFP98cQXxBCpthd5aZ
/RARYjtP7SqL1bmUeS9PDUopHL5NxgD7AweoFsYMBOCeH/mcR9ybj/wQ6BBwH2dZrULKUgKeixKl
UkkziftRVCopixvgxaAt+bYcPoml+mBtVk3p1JBOw9gxrTUxraNu1d/mwXIW8a7Juqa12S23wcKt
vXFI4LWvxtOQvN0nrkeIQf+uAswqdZUiPv2UPgD6Bw+wfgEAAA==
EOF
(cd rust-s20110505
PATH="$base"/llvm-3.0svn-1/Release+Asserts/bin:"$PATH" ./configure \
    --disable-docs)
make -C rust-s20110505 -j8 stage2/rustc
(cd rust-s20110505; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
