#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120620 \
    b02172971fa658f2e6d3cdb3cbf3bf663801d656
git -C rust-s20120620 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120620/src/libuv
install -Dt rust-s20120620/dl rust-s20120607/$(< rust-s20120607/snap.txt)
cat > rust-s20120620/src/snapshots.txt <<EOF
S 2012-06-07 $(cut -f 6 -d - rust-s20120607/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120607/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120620
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -248 +248 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -668 +668 @@
-    explicit ptr(uint8_t *in_p) : p(in_p) {}
+    ptr(uint8_t *in_p) : p(in_p) {}
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
