#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111206 \
    1652b921fa2fadc936b346fc3de217cf97b0e476
git -C rust-s20111206 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20111206/src/libuv
mkdir rust-s20111206/dl
cp rust-s20111130/$(< rust-s20111130/snap.txt) rust-s20111206/dl
cat > rust-s20111206/src/snapshots.txt <<EOF
S 2011-11-30 0ed5c84
  linux-x86_64 $(cut -c 45-84 rust-s20111130/snap.txt)
EOF
cd rust-s20111206
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -205 +205 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -100,0 +101 @@
+#define alignof rust_alignof
@@ -883 +884 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-3/Release+Asserts
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
