#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130917 \
    cbd1eefbd350797b783df119fed7956d7e1c74ad
git -C rust-s20130917 config --worktree core.abbrev 7
git -C libuv archive v0.11.11 | tar -xf - -C rust-s20130917/src/libuv
git -C gyp archive f407f09c94e00d2d570e8e42114e3f6848b2deb2 | tar -xf - -C rust-s20130917/src/gyp
cd rust-s20130917
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -545 +545 @@
-	(3.3|3.3svn|3.2|3.2svn)
+	(3.4svn|3.3|3.3svn|3.2|3.2svn)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -150 +150 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
patch -p1 <<EOF
--- a/src/libextra/terminfo/searcher.rs
+++ b/src/libextra/terminfo/searcher.rs
@@ -50 +49,0 @@
-                    dirs_to_search.push(path("/lib/terminfo"));
EOF
patch -p1 <<EOF
--- a/src/libuv/gyp_uv
+++ b/src/libuv/gyp_uv
@@ -34 +34 @@
-  proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
+  proc = subprocess.Popen(CC.split() + ['-dumpfullversion'], stdout=subprocess.PIPE)
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130814/x86_64-unknown-linux-gnu/stage1 \
    --llvm-root="$base"/llvm-3.4svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
