#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20121102 \
    4876eb708c122567a9b4bb47667d14d262b181e4
git -C rust-s20121102 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20121102/src/libuv
cd rust-s20121102
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -448 +448 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -248 +248 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -657 +657 @@
-    explicit ptr(uint8_t *in_p) : p(in_p) {}
+    ptr(uint8_t *in_p) : p(in_p) {}
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20121008/x86_64-unknown-linux-gnu/stage2 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc
printf '\a'
