#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-t20110516 \
    ae030c5bf277e90b9aeea7e301fd3001f3a66b8d
git -C rust-t20110516 config --worktree core.abbrev 7
mkdir rust-t20110516/dl
cp rust-s20110512/$(< rust-s20110512/snap.txt) rust-t20110516/dl
cat > rust-t20110516/src/snapshots.txt <<EOF
S 2011-05-12 b1d3364
  linux-i386 $(cut -c 43-82 rust-s20110512/snap.txt)
EOF
patch -d rust-t20110516 -p1 <<'EOF'
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
(cd rust-t20110516
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-t20110516 -j8 stage1/rustc
(cd rust-t20110516; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
