#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111012 \
    40fa88febb0eef3010b27e85d1ffac32a2d162f5
git -C rust-s20111012 config --worktree core.abbrev 7
mkdir rust-s20111012/dl
cp rust-s20111006/$(< rust-s20111006/snap.txt) rust-s20111012/dl
cat > rust-s20111012/src/snapshots.txt <<EOF
S 2011-10-06 $(cut -f 6 -d - rust-s20111006/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20111006/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20111012
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -180 +180 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
