#!/bin/bash
base=$(pwd)
# sudo apt-get install -y ocaml-nox python-is-python2
# git clone https://github.com/rust-lang/rust.git
# git -C rust config extensions.worktreeConfig true
git -C rust worktree add "$base"/rust-s20110503 \
    54bfe8ee27b2a2958fec5e9713690a4336d8b4e4
git -C rust-s20110503 config --worktree core.abbrev 7
patch -d rust-s20110503 -p1 <<'EOF'
--- a/mk/boot.mk
+++ b/mk/boot.mk
@@ -58 +58 @@
-BOOT_ML_NATIVE_LIBS := unix.cmxa nums.cmxa bigarray.cmxa
+BOOT_ML_NATIVE_LIBS := unix.cmxa bigarray.cmxa
@@ -60 +60 @@
-BOOT_OCAMLOPT_FLAGS := -g $(BOOT_ML_INCS) -w Ael -warn-error Ael
+BOOT_OCAMLOPT_FLAGS := -g $(BOOT_ML_INCS) -w Ael
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -136 +136 @@
-  CFG_GCC_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCC_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-   $(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+   $(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -ldl -lpthread,$(RUNTIME_DEF))
--- a/src/boot/be/asm.ml
+++ b/src/boot/be/asm.ml
@@ -670,5 +670,5 @@
-  let arr = (Bigarray.Array1.map_file
-               fd ~pos:0L
-               Bigarray.int8_unsigned
-               Bigarray.c_layout
-               false (-1))
+  let arr = Bigarray.array1_of_genarray (Unix.map_file
+                                           fd ~pos:0L
+                                           Bigarray.int8_unsigned
+                                           Bigarray.c_layout
+                                           false [| -1 |])
--- a/src/boot/fe/fuzz.ml
+++ b/src/boot/fe/fuzz.ml
@@ -33 +33 @@
-    s
+    Bytes.to_string s
--- a/src/etc/snapshot.py
+++ b/src/etc/snapshot.py
@@ -115 +115 @@
-      tar.add(os.path.join("stage2", name),
+      tar.add(os.path.join("stage1", name),
EOF
(cd rust-s20110503
PATH="$base"/llvm-3.0svn-1/Release+Asserts/bin:"$PATH" ./configure \
    --disable-docs)
make -C rust-s20110503 -j8 stage1/rustc
(cd rust-s20110503; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
