#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110819 \
    390dd3861933db71339dba01f09a83594a85d3eb
git -C rust-s20110819 config --worktree core.abbrev 7
mkdir rust-s20110819/dl
cp rust-s20110816/$(< rust-s20110816/snap.txt) rust-s20110819/dl
cat > rust-s20110819/src/snapshots.txt <<EOF
S 2011-08-16 014c692
  linux-i386 $(cut -c 43-82 rust-s20110816/snap.txt)
EOF
cd rust-s20110819
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -156 +156 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -559 +559 @@
-        ~[stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        ~[stage, glu, "-m32", "-o", saved_out_filename,
@@ -614,0 +615 @@
+    gcc_args += ~["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.cpp
+++ b/src/rt/rust_shape.cpp
@@ -946 +946 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -211 +211 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-6/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
