#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111117-1 \
    a92699fe585f1f02a300d69620c0a098b1e12d9c
git -C rust-s20111117-1 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20111117-1/src/libuv
mkdir rust-s20111117-1/dl
cp rust-s20111116-2/$(< rust-s20111116-2/snap.txt) rust-s20111117-1/dl
cat > rust-s20111117-1/src/snapshots.txt <<EOF
S 2011-11-16 045a437
  linux-i386 $(cut -c 43-82 rust-s20111116-2/snap.txt)
EOF
cd rust-s20111117-1
patch -p1 <<'EOF'
--- a/configure
+++ b/configure
@@ -413 +413 @@
-if [ $NEED_INIT ]
+if false
@@ -419 +419 @@
-if [ $NEED_UPDATE ]
+if false
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -204 +204 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -99,0 +100 @@
+#define alignof rust_alignof
@@ -882 +883 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --llvm-root="$base"/llvm-3.1svn-1/Release+Asserts
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
