#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120621 \
    a141f58e9b34a3f8ab68b5d7f9db8b2d75492d78
git -C rust-s20120621 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120621/src/libuv
install -Dt rust-s20120621/dl rust-s20120620/$(< rust-s20120620/snap.txt)
cat > rust-s20120621/src/snapshots.txt <<EOF
S 2012-06-20 b021729
  linux-x86_64 $(cut -c 45-84 rust-s20120620/snap.txt)
EOF
cd rust-s20120621
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -248 +248 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -665 +665 @@
-    explicit ptr(uint8_t *in_p) : p(in_p) {}
+    ptr(uint8_t *in_p) : p(in_p) {}
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
