#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111006 \
    e4068f67153807f4c2554600bc60d2b3699ce682
git -C rust-s20111006 config --worktree core.abbrev 7
mkdir rust-s20111006/dl
cp rust-s20110930/$(< rust-s20110930/snap.txt) rust-s20111006/dl
cat > rust-s20111006/src/snapshots.txt <<EOF
S 2011-09-30 821dd6c
  linux-i386 $(cut -c 43-82 rust-s20110930/snap.txt)
EOF
cd rust-s20111006
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -181 +181 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
