#!/bin/bash
mkdir llvm-3.1svn-4
git -C llvm-project archive 2937df45a811273c198c4795a3dc11fe7e784424 llvm |
tar -xf - -C llvm-3.1svn-4 --strip-components=1
cd llvm-3.1svn-4
patch -p1 <<EOF
--- a/tools/bugpoint/ToolRunner.cpp
+++ b/tools/bugpoint/ToolRunner.cpp
@@ -131 +131 @@
-    errs() << OS;
+    errs() << OS.str();
EOF
./configure --disable-jit --disable-docs --disable-threads --disable-pthreads \
    --enable-targets=x86_64 --enable-bindings=none
make -j8
printf '\a'
