#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110512 \
    b1d3364487eb647f2d7fcb412a260c960e38c73e
git -C rust-s20110512 config --worktree core.abbrev 7
mkdir rust-s20110512/dl
cp rust-s20110506/$(< rust-s20110506/snap.txt) rust-s20110512/dl
cat > rust-s20110512/src/snapshots.txt <<EOF
S 2011-05-06 $(cut -f 6 -d - rust-s20110506/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110506/snap.txt | cut -f 1 -d .)
EOF
patch -d rust-s20110512 -p1 <<'EOF'
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -153 +153 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
--- a/src/etc/snapshot.py
+++ b/src/etc/snapshot.py
@@ -115 +115 @@
-      tar.add(os.path.join("stage2", name),
+      tar.add(os.path.join("stage1", name),
EOF
(cd rust-s20110512
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110512 -j8 stage1/rustc
(cd rust-s20110512; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
