#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111130 \
    0ed5c84403cdbfb4bc5485b05a97eebe20af34e1
git -C rust-s20111130 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20111130/src/libuv
mkdir rust-s20111130/dl
cp rust-s20111124/$(< rust-s20111124/snap.txt) rust-s20111130/dl
cat > rust-s20111130/src/snapshots.txt <<EOF
S 2011-11-24 05b2cb8
  linux-i386 $(cut -c 43-82 rust-s20111124/snap.txt)
EOF
cd rust-s20111130
mkdir llvm
ln -s "$base"/llvm-3.1svn-1 llvm/i686-unknown-linux-gnu
ln -s "$base"/llvm-3.1svn-2 llvm/x86_64-unknown-linux-gnu
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -205 +205 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -100,0 +101 @@
+#define alignof rust_alignof
@@ -883 +884 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --disable-manage-submodules \
    --target-triples=i686-unknown-linux-gnu,x86_64-unknown-linux-gnu
make -j8 snap-stage1-H-x86_64-unknown-linux-gnu
echo rust-stage0* > snap.txt
printf '\a'
