#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110707-2 \
    64595a53f826b0fd8890707d0e63c119116f2a27
git -C rust-s20110707-2 config --worktree core.abbrev 7
mkdir rust-s20110707-2/dl
cp rust-s20110707-1/$(< rust-s20110707-1/snap.txt) rust-s20110707-2/dl
cat > rust-s20110707-2/src/snapshots.txt <<EOF
S 2011-07-07 $(cut -f 6 -d - rust-s20110707-1/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110707-1/snap.txt | cut -f 1 -d .)
EOF
patch -d rust-s20110707-2 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110707-2 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -98 +98 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-s20110707-2 -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -484 +484 @@
-        [stage, "-Lrt", "-lrustrt", glu,  "-m32", "-o",
+        [stage, glu,  "-m32", "-o",
@@ -539,0 +540 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -d rust-s20110707-2 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -205 +205 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-s20110707-2
PATH="$base"/llvm-3.0svn-4/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110707-2 -j8 stage2/lib/libstd.rlib stage2/lib/libstd.so
(cd rust-s20110707-2; CFG_SRC_DIR=. src/etc/make-snapshot.py stage2 > snap.txt)
printf '\a'
