#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130321 \
    ed25a674ac6bc53c9ee9f8c1cce21541f6811d4b
git -C rust-s20130321 config --worktree core.abbrev 7
git -C libuv archive v0.11.5 | tar -xf - -C rust-s20130321/src/libuv
cd rust-s20130321
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -500 +500 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -124 +124 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130227/x86_64-unknown-linux-gnu/stage1 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
