#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110829 \
    c9c5ee252a8523778377f2832765442e611e85a4
git -C rust-s20110829 config --worktree core.abbrev 7
mkdir rust-s20110829/dl
cp rust-s20110827/$(< rust-s20110827/snap.txt) rust-s20110829/dl
cat > rust-s20110829/src/snapshots.txt <<EOF
S 2011-08-27 5f57a50
  linux-i386 $(cut -c 43-82 rust-s20110827/snap.txt)
EOF
cd rust-s20110829
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -163 +163 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -576 +576 @@
-         ~"-Lrt", ~"-lrustrt", glu,
+         glu,
@@ -633,0 +634 @@
+    gcc_args += [~"-Lrt", ~"-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_crate_cache.cpp
+++ b/src/rt/rust_crate_cache.cpp
@@ -2 +1,0 @@
-#include "rust_internal.h"
@@ -3,0 +3,2 @@
+#include "rust_internal.h"
+#undef max
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -787 +787 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
