#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110506 \
	ab437253d3414ac7be2d94f76a2af4386b4991bf
git -C rust-s20110506 config --worktree core.abbrev 7
mkdir rust-s20110506/dl
cp rust-s20110505/$(< rust-s20110505/snap.txt) rust-s20110506/dl
cat > rust-s20110506/src/snapshots.txt <<EOF
S 2011-05-05 $(cut -f 6 -d - rust-s20110505/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110505/snap.txt | cut -f 1 -d .)
EOF
patch -d rust-s20110506 -p1 <<'EOF'
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -137 +137 @@
-  CFG_GCC_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCC_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
--- a/src/etc/snapshot.py
+++ b/src/etc/snapshot.py
@@ -115 +115 @@
-      tar.add(os.path.join("stage2", name),
+      tar.add(os.path.join("stage1", name),
EOF
(cd rust-s20110506
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110506 -j8 stage1/rustc
(cd rust-s20110506; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
