#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110901-1 \
    91ea2577cdea160f13b617546a00b39518be35e9
git -C rust-s20110901-1 config --worktree core.abbrev 7
mkdir rust-s20110901-1/dl
cp rust-s20110830/$(< rust-s20110830/snap.txt) rust-s20110901-1/dl
cat > rust-s20110901-1/src/snapshots.txt <<EOF
S 2011-08-30 $(cut -f 6 -d - rust-s20110830/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110830/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20110901-1
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -163 +163 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -579 +579 @@
-         ~"-Lrt", ~"-lrustrt", glu,
+         glu,
@@ -636,0 +637 @@
+    gcc_args += [~"-Lrt", ~"-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_crate_cache.cpp
+++ b/src/rt/rust_crate_cache.cpp
@@ -2 +1,0 @@
-#include "rust_internal.h"
@@ -3,0 +3,2 @@
+#include "rust_internal.h"
+#undef max
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -92,0 +93 @@
+#define alignof rust_alignof
@@ -846 +847 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
