#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20140108 \
    f3a8baafbecdb6e41f001c8f218d4796a9ca8d40
git -C rust-s20140108 config --worktree core.abbrev 7
git -C libuv archive v0.11.19 | tar -xf - -C rust-s20140108/src/libuv
git -C gyp archive master | tar -xf - -C rust-s20140108/src/gyp
cd rust-s20140108
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -153 +153 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
patch -p1 <<EOF
--- a/src/libuv/gyp_uv.py
+++ b/src/libuv/gyp_uv.py
@@ -34 +34 @@
-  proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
+  proc = subprocess.Popen(CC.split() + ['-dumpfullversion'], stdout=subprocess.PIPE)
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20140105/x86_64-unknown-linux-gnu/stage1 \
    --llvm-root="$base"/llvm-3.4svn-1/Release+Asserts
make -j8 rustc
printf '\a'
