#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110912-2 \
    3667137a4104ecde5c37f128d6d8c6080529f89f
git -C rust-s20110912-2 config --worktree core.abbrev 7
mkdir rust-s20110912-2/dl
cp rust-s20110912-1/$(< rust-s20110912-1/snap.txt) rust-s20110912-2/dl
cat > rust-s20110912-2/src/snapshots.txt <<EOF
S 2011-09-12 8b7909a
  linux-i386 $(cut -c 43-82 rust-s20110912-1/snap.txt)
EOF
cd rust-s20110912-2
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -163 +163 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -549 +549 @@
-        [stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        [stage, glu, "-m32", "-o", saved_out_filename,
@@ -605,0 +606 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_crate_cache.cpp
+++ b/src/rt/rust_crate_cache.cpp
@@ -2 +1,0 @@
-#include "rust_internal.h"
@@ -3,0 +3,2 @@
+#include "rust_internal.h"
+#undef max
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -91,0 +92 @@
+#define alignof rust_alignof
@@ -819 +820 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
