#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120323-2 \
    a84b56bc70b2fc68bae4ef686063996149ad6954
git -C rust-s20120323-2 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120323-2/src/libuv
mkdir rust-s20120323-2/dl
cp rust-s20120323-1/$(< rust-s20120323-1/snap.txt) rust-s20120323-2/dl
cat > rust-s20120323-2/src/snapshots.txt <<EOF
S 2012-03-23 6374ffc
  linux-x86_64 $(cut -c 45-84 rust-s20120323-1/snap.txt)
EOF
cd rust-s20120323-2
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -235 +235 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
