#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110729 \
    5adf87a2c6418b1056e0cc45edb3645f840cfac7
git -C rust-s20110729 config --worktree core.abbrev 7
mkdir rust-s20110729/dl
cp rust-t20110727/$(< rust-t20110727/snap.txt) rust-s20110729/dl
cat > rust-s20110729/src/snapshots.txt <<EOF
T 2011-07-27 $(cut -f 6 -d - rust-t20110727/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-t20110727/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20110729
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -151 +151 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -99 +99 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -529 +529 @@
-        [stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        [stage, glu, "-m32", "-o", saved_out_filename,
@@ -585,0 +586 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -211 +211 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-5/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
