#!/bin/bash
mkdir llvm-3.4svn-1
git -C rust-llvm archive alexcrichton/rust-llvm-2013-09-15 |
tar -xf - -C llvm-3.4svn-1
cd llvm-3.4svn-1
./configure --disable-jit --disable-docs --enable-targets=x86_64,arm,mips \
    --enable-bindings=none --disable-terminfo --enable-optimized
make -j8
printf '\a'
