#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110815 \
    42034f5e345838e1ae5b26c36326289b72b467f0
git -C rust-s20110815 config --worktree core.abbrev 7
mkdir rust-s20110815/dl
cp rust-s20110814/$(< rust-s20110814/snap.txt) rust-s20110815/dl
cat > rust-s20110815/src/snapshots.txt <<EOF
S 2011-08-14 83128f4
  linux-i386 $(cut -c 43-82 rust-s20110814/snap.txt)
EOF
cd rust-s20110815
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -156 +156 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -561 +561 @@
-        ~[stage, "-Lrt", "-lrustrt", glu, "-m32", "-o", saved_out_filename,
+        ~[stage, glu, "-m32", "-o", saved_out_filename,
@@ -616,0 +617 @@
+    gcc_args += ~["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.cpp
+++ b/src/rt/rust_shape.cpp
@@ -957 +957 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -212 +212 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-6/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
