#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120111 \
    f2352f406221914396de0894e1d94a395cfd583d
git -C rust-s20120111 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20120111/src/libuv
mkdir rust-s20120111/dl
cp rust-s20120109/$(< rust-s20120109/snap.txt) rust-s20120111/dl
cat > rust-s20120111/src/snapshots.txt <<EOF
S 2012-01-09 d4ae1ca
  linux-x86_64 $(cut -c 45-84 rust-s20120109/snap.txt)
EOF
cd rust-s20120111
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -212 +212 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -102,0 +103 @@
+#define alignof rust_alignof
@@ -895 +896 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-3/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
