#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120105 \
    3eb35900c7f0b1c95455fb2088977b9ac468c96c
git -C rust-s20120105 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20120105/src/libuv
mkdir rust-s20120105/dl
cp rust-s20111222/$(< rust-s20111222/snap.txt) rust-s20120105/dl
cat > rust-s20120105/src/snapshots.txt <<EOF
S 2011-12-22 3b61064
  linux-x86_64 $(cut -c 45-84 rust-s20111222/snap.txt)
EOF
cd rust-s20120105
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -212 +212 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -100,0 +101 @@
+#define alignof rust_alignof
@@ -882 +883 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-3/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
