#!/bin/bash
base=$(pwd)
git -C rust worktree add -f "$base"/rust-t20110516 \
    ae030c5bf277e90b9aeea7e301fd3001f3a66b8d
git -C rust-t20110516 config --worktree core.abbrev 7
mkdir rust-t20110516/dl
cp rust-s20110512/$(< rust-s20110512/snap.txt) rust-t20110516/dl
cat > rust-t20110516/src/snapshots.txt <<EOF
S 2011-05-12 b1d3364
  linux-i386 $(cut -c 43-82 rust-s20110512/snap.txt)
EOF
base64 -d <<EOF | zcat | patch -d rust-t20110516 -p1
H4sIAAAAAAAAA52OSQvCMBCFz/ZXzCGHhnQUQehJiEZb64pW8ViixoWuxBz8+bYUcQMPXh7z3jBv
PkQE2UrjVpFIc8x12kxjizEGu8+Qc8B2xwVWCecWAgjPj3whgnAUCW/a80NgXcCtTJJSlda5Bjxm
OWpjLvWkbntVmEueXQFPFvtd8esUH9zavBHXtmJ1S1S3Jm0Qe0mJva9aq4fTYD6JhEO4Q+zVZr4O
ZsMy64cUnn7RH4f0ZT8YepRa7O8qwKQwZ63k4av0DullxheEAQAA
EOF
(cd rust-t20110516
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-t20110516 -j8 stage1/rustc
(cd rust-t20110516; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
