#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120427 \
    09624a676a975326ae7d7e25e7050b6cc22161e9
git -C rust-s20120427 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120427/src/libuv
mkdir rust-s20120427/dl
cp rust-s20120423/$(< rust-s20120423/snap.txt) rust-s20120427/dl
cat > rust-s20120427/src/snapshots.txt <<EOF
S 2012-04-23 b04b415
  linux-x86_64 $(cut -c 45-84 rust-s20120423/snap.txt)
EOF
cd rust-s20120427
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
