#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120414 \
    eb935b8fcbe1ceb128797aa574e0c1a332a6a14e
git -C rust-s20120414 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120414/src/libuv
mkdir rust-s20120414/dl
cp rust-s20120404/$(< rust-s20120404/snap.txt) rust-s20120414/dl
cat > rust-s20120414/src/snapshots.txt <<EOF
S 2012-04-04 $(cut -f 6 -d - rust-s20120404/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120404/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120414
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
