#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110521 \
    085fb1a2db2f8d77e215571151c323433a5c6381
git -C rust-s20110521 config --worktree core.abbrev 7
mkdir rust-s20110521/dl
cp rust-s20110520/$(< rust-s20110520/snap.txt) rust-s20110521/dl
cat > rust-s20110521/src/snapshots.txt <<EOF
S 2011-05-20 $(cut -f 6 -d - rust-s20110520/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110520/snap.txt | cut -f 1 -d .)
EOF
patch -d rust-s20110521 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110521 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
(cd rust-s20110521
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110521 -j8 stage1/rustc
(cd rust-s20110521; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
