#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120114 \
    c6f62b637422783fc44de92e4011344e46f17498
git -C rust-s20120114 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20120114/src/libuv
mkdir rust-s20120114/dl
cp rust-s20120112/$(< rust-s20120112/snap.txt) rust-s20120114/dl
cat > rust-s20120114/src/snapshots.txt <<EOF
S 2012-01-12 $(cut -f 6 -d - rust-s20120112/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120112/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120114
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -212 +212 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -107,0 +108 @@
+#define alignof rust_alignof
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
