#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110629 \
    865534978fdd9da9cc5dd1dbf608206810bc8dee
git -C rust-s20110629 config --worktree core.abbrev 7
mkdir rust-s20110629/dl
cp rust-s20110617/$(< rust-s20110617/snap.txt) rust-s20110629/dl
cat > rust-s20110629/src/snapshots.txt <<EOF
S 2011-06-17 175fd8e
  linux-i386 $(cut -c 43-82 rust-s20110617/snap.txt)
EOF
patch -d rust-s20110629 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -150 +150 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110629 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -98 +98 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-s20110629 -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -404 +404 @@
-            [stage, "-Lrt", "-lrustrt", glu,  "-m32", "-o",
+            [stage, glu,  "-m32", "-o",
@@ -466,0 +467 @@
+        gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -d rust-s20110629 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -205 +205 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-s20110629
PATH="$base"/llvm-3.0svn-3/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110629 -j8 stage2/lib/libstd.so
(cd rust-s20110629; CFG_SRC_DIR=. src/etc/make-snapshot.py stage2 > snap.txt)
printf '\a'
