#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110505 \
    157f61f8c871e0fd63a57fe63821360d0a0d95fe
git -C rust-s20110505 config --worktree core.abbrev 7
mkdir rust-s20110505/dl
cp rust-s20110503/$(< rust-s20110503/snap.txt) rust-s20110505/dl
cat > rust-s20110505/src/snapshots.txt <<EOF
S 2011-05-03 54bfe8e
  linux-i386 $(cut -c 43-82 rust-s20110503/snap.txt)
EOF
patch -d rust-s20110505 -p1 <<'EOF'
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -137 +137 @@
-  CFG_GCC_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCC_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -77 +77 @@
-   $(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+   $(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
(cd rust-s20110505
PATH="$base"/llvm-3.0svn-1/Release+Asserts/bin:"$PATH" ./configure \
    --disable-docs)
make -C rust-s20110505 -j8 stage2/rustc
(cd rust-s20110505; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
