#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20121126 \
    be6613e048c889a0aeaff056131c2406259f1fb4
git -C rust-s20121126 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20121126/src/libuv
cd rust-s20121126
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -457 +457 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -261 +261 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -g
+  CFG_GCCISH_CFLAGS += -Wall -g
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20121102/x86_64-unknown-linux-gnu/stage2 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc
printf '\a'
