#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110929 \
    80829af8723aa1289a180734915848c1dda38b2d
git -C rust-s20110929 config --worktree core.abbrev 7
mkdir rust-s20110929/dl
cp rust-s20110928/$(< rust-s20110928/snap.txt) rust-s20110929/dl
cat > rust-s20110929/src/snapshots.txt <<EOF
S 2011-09-28 $(cut -f 6 -d - rust-s20110928/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110928/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20110929
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -173 +173 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/comp/back/link.rs
+++ b/src/comp/back/link.rs
@@ -520 +520 @@
-        [stage, "-Lrt", "-lrustrt", "-m32", "-o", saved_out_filename,
+        [stage, "-m32", "-o", saved_out_filename,
@@ -576,0 +577 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.0svn-7/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
