#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-head-02c0501 \
    02c0501a6185da2d3bfce2be1b2bc02abbd36bb9
git -C rust-head-02c0501 config --worktree core.abbrev 7
mkdir rust-head-02c0501/dl
cp rust-s20110615-2/$(< rust-s20110615-2/snap.txt) rust-head-02c0501/dl
cat > rust-head-02c0501/src/snapshots.txt <<EOF
S 2011-06-15 92bd350
  linux-i386 $(cut -c 43-82 rust-s20110615-2/snap.txt)
EOF
patch -d rust-head-02c0501 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-head-02c0501 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -96 +96 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-head-02c0501 -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -402 +402 @@
-        let vec[str] common_args = [stage, "-Lrt", "-lrustrt",
+        let vec[str] common_args = [stage,
@@ -427,0 +428 @@
+        gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -d rust-head-02c0501 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -201 +201 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-head-02c0501
PATH="$base"/llvm-3.0svn-3/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-head-02c0501 -j8 stage1/rustc
(cd rust-head-02c0501; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
