#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120315-1 \
    1745ac9c61010b416673070d466b5007ed48540b
git -C rust-s20120315-1 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120315-1/src/libuv
mkdir rust-s20120315-1/dl
cp rust-s20120313/$(< rust-s20120313/snap.txt) rust-s20120315-1/dl
cat > rust-s20120315-1/src/snapshots.txt <<EOF
S 2012-03-13 $(cut -f 6 -d - rust-s20120313/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120313/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120315-1
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -238 +238 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
