#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120320 \
    8404ea0c8af1e5006faa8aad0b4b2ab718204902
git -C rust-s20120320 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120320/src/libuv
mkdir rust-s20120320/dl
cp rust-s20120316/$(< rust-s20120316/snap.txt) rust-s20120320/dl
cat > rust-s20120320/src/snapshots.txt <<EOF
S 2012-03-16 $(cut -f 6 -d - rust-s20120316/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120316/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120320
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -238 +238 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
