#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120215 \
    9e685005d414565a8fcace069bc1149f53b71966
git -C rust-s20120215 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120215/src/libuv
mkdir rust-s20120215/dl
cp rust-s20120212/$(< rust-s20120212/snap.txt) rust-s20120215/dl
cat > rust-s20120215/src/snapshots.txt <<EOF
S 2012-02-12 2784314
  linux-x86_64 $(cut -c 45-84 rust-s20120212/snap.txt)
EOF
cd rust-s20120215
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -229 +229 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -6,0 +7 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -108,0 +109 @@
+#define alignof rust_alignof
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
