#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110506 \
	ab437253d3414ac7be2d94f76a2af4386b4991bf
git -C rust-s20110506 config --worktree core.abbrev 7
mkdir rust-s20110506/dl
cp rust-s20110505/$(< rust-s20110505/snap.txt) rust-s20110506/dl
cat > rust-s20110506/src/snapshots.txt <<EOF
S 2011-05-05 157f61f
  linux-i386 $(cut -c 43-82 rust-s20110505/snap.txt)
EOF
base64 -d <<EOF | zcat | patch -d rust-s20110506 -p1
H4sIAAAAAAAAA52RXUvDMBSGr+2vOIxeJKRpqSK7EurqWqZzolW8LLHN1rq2CUku9N+brMr8YoKB
HM43T/JSSoFF/TaSHTNrofqw33qEEHj6nkwSoPHJFIgzSeJRgDTLyzxNyzRbnucFkDOgj6zrrOVK
CQV0PQiqjGlHj79UXJpWDBroxiMH5g/N0Q9iZb6wjqGjnFpIex3jkY9usY8qR+Vol4vVVZkGfhL4
6O5hdb+4ntvcrMCwj29mlwX+VL+YZxh75N+rgHbSNIqz+sfS8S1aVRE3VaQHJnUjTChf3yX4rbLT
IT61Olgz6uCOYSpkdY2EDiUzTfgs2gFNtGEbfjwJYGA9x4H79D+a433zGzdz3QUcAgAA
EOF
(cd rust-s20110506
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110506 -j8 stage1/rustc
(cd rust-s20110506; CFG_SRC_DIR=. src/etc/make-snapshot.py > snap.txt)
printf '\a'
