#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120315-2 \
    c86135e80b66e795a156070883a0545f6fdd3cae
git -C rust-s20120315-2 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120315-2/src/libuv
mkdir rust-s20120315-2/dl
cp rust-s20120315-1/$(< rust-s20120315-1/snap.txt) rust-s20120315-2/dl
cat > rust-s20120315-2/src/snapshots.txt <<EOF
S 2012-03-15 $(cut -f 6 -d - rust-s20120315-1/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120315-1/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120315-2
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -238 +238 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
