#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130204 \
    2f46b763da2c098913884f101b6d71d69af41b49
git -C rust-s20130204 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20130204/src/libuv
cd rust-s20130204
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -496 +496 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -271 +271 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -g
+  CFG_GCCISH_CFLAGS += -Wall -g
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130123/x86_64-unknown-linux-gnu/stage2 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc
printf '\a'
