#!/bin/bash
mkdir llvm-3.0svn-4
git -C llvm-project archive d91d566d7f1cd7fbda98205bd9c9d64d9c7175e0 llvm |
tar -xf - -C llvm-3.0svn-4 --strip-components=1
patch -d llvm-3.0svn-4 -p1 <<EOF
--- a/include/llvm/ADT/IntervalMap.h
+++ b/include/llvm/ADT/IntervalMap.h
@@ -1977 +1977 @@
-    Node[NewNode] = this->map->newNode<NodeT>();
+    Node[NewNode] = this->map->template newNode<NodeT>();
--- a/include/llvm/ADT/PointerUnion.h
+++ b/include/llvm/ADT/PointerUnion.h
@@ -262 +262 @@
-      return Ty(Val).is<T>();
+      return Ty(Val).template is<T>();
@@ -275 +275 @@
-      return Ty(Val).get<T>();
+      return Ty(Val).template get<T>();
--- a/lib/ExecutionEngine/JIT/Intercept.cpp
+++ b/lib/ExecutionEngine/JIT/Intercept.cpp
@@ -54,0 +55 @@
+#include <unistd.h>
--- a/lib/ExecutionEngine/MCJIT/Intercept.cpp
+++ b/lib/ExecutionEngine/MCJIT/Intercept.cpp
@@ -54,0 +55 @@
+#include <unistd.h>
--- a/lib/Target/X86/X86CodeEmitter.cpp
+++ b/lib/Target/X86/X86CodeEmitter.cpp
@@ -569 +569 @@
-  static const unsigned SSTable[] = { ~0, 0, 1, ~0, 2, ~0, ~0, ~0, 3 };
+  static const unsigned SSTable[] = { ~0U, 0, 1, ~0U, 2, ~0U, ~0U, ~0U, 3 };
--- a/lib/Target/X86/X86MCCodeEmitter.cpp
+++ b/lib/Target/X86/X86MCCodeEmitter.cpp
@@ -349 +349 @@
-  static const unsigned SSTable[] = { ~0, 0, 1, ~0, 2, ~0, ~0, ~0, 3 };
+  static const unsigned SSTable[] = { ~0U, 0, 1, ~0U, 2, ~0U, ~0U, ~0U, 3 };
--- a/tools/bugpoint/ToolRunner.cpp
+++ b/tools/bugpoint/ToolRunner.cpp
@@ -131 +131 @@
-    errs() << OS;
+    errs() << OS.str();
EOF
(cd llvm-3.0svn-4
./configure --build=i686-unknown-linux-gnu --disable-jit --disable-docs \
    --disable-threads --disable-pthreads --enable-targets=x86 \
    --enable-bindings=none)
make -C llvm-3.0svn-4 -j8 CC='gcc -m32' CXX='g++ -m32'
printf '\a'
