#!/bin/bash
mkdir llvm-3.1svn-2
git -C llvm-project archive ec2fb226d8b84ee1090f7d7fa2e0da6232fee469 llvm |
tar -xf - -C llvm-3.1svn-2 --strip-components=1
cd llvm-3.1svn-2
patch -p1 <<EOF
--- a/include/llvm/ADT/IntervalMap.h
+++ b/include/llvm/ADT/IntervalMap.h
@@ -1980 +1980 @@
-    Node[NewNode] = this->map->newNode<NodeT>();
+    Node[NewNode] = this->map->template newNode<NodeT>();
--- a/include/llvm/ADT/PointerUnion.h
+++ b/include/llvm/ADT/PointerUnion.h
@@ -266 +266 @@
-      return Ty(Val).is<T>();
+      return Ty(Val).template is<T>();
@@ -279 +279 @@
-      return Ty(Val).get<T>();
+      return Ty(Val).template get<T>();
--- a/tools/bugpoint/ToolRunner.cpp
+++ b/tools/bugpoint/ToolRunner.cpp
@@ -131 +131 @@
-    errs() << OS;
+    errs() << OS.str();
EOF
./configure --disable-jit --disable-docs --disable-threads --disable-pthreads \
    --enable-targets=x86_64 --enable-bindings=none
make -j8
printf '\a'
