#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110827 \
    5f57a508af9c43adc03a4edd575ceae41cc8cd3a
git -C rust-s20110827 config --worktree core.abbrev 7
mkdir rust-s20110827/dl
cp rust-s20110826/$(< rust-s20110826/snap.txt) rust-s20110827/dl
cat > rust-s20110827/src/snapshots.txt <<EOF
S 2011-08-26 $(cut -f 6 -d - rust-s20110826/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110826/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20110827
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -163 +163 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -576 +576 @@
-         ~"-Lrt", ~"-lrustrt", glu,
+         glu,
@@ -633,0 +634 @@
+    gcc_args += [~"-Lrt", ~"-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_crate_cache.cpp
+++ b/src/rt/rust_crate_cache.cpp
@@ -2 +1,0 @@
-#include "rust_internal.h"
@@ -3,0 +3,2 @@
+#include "rust_internal.h"
+#undef max
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -787 +787 @@
-    void walk_number(bool align) { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number(bool align) { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -211 +211 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-6/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
