#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110615-1 \
    01ea27b205817ee952f7132b2663701622aa6c69
git -C rust-s20110615-1 config --worktree core.abbrev 7
mkdir rust-s20110615-1/dl
cp rust-s20110609/$(< rust-s20110609/snap.txt) rust-s20110615-1/dl
cat > rust-s20110615-1/src/snapshots.txt <<EOF
S 2011-06-09 efcf857
  linux-i386 $(cut -c 43-82 rust-s20110609/snap.txt)
EOF
patch -d rust-s20110615-1 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -25 +25 @@
-  CFG_GCCISH_CFLAGS += -fPIC -march=i686 -O2
+  CFG_GCCISH_CFLAGS += -fPIC -march=i686
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110615-1 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -96 +96 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -d rust-s20110615-1 -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -201 +201 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
(cd rust-s20110615-1
PATH="$base"/llvm-3.0svn-3/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110615-1 -j8 stage1/rustc
(cd rust-s20110615-1; CFG_SRC_DIR=. src/etc/make-snapshot.py stage1 > snap.txt)
printf '\a'
