#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120607 \
    3cbd1e221ec9625e7879adb3fe406efd082cb60d
git -C rust-s20120607 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120607/src/libuv
install -Dt rust-s20120607/dl rust-s20120604/$(< rust-s20120604/snap.txt)
cat > rust-s20120607/src/snapshots.txt <<EOF
S 2012-06-04 7213274
  linux-x86_64 $(cut -c 45-84 rust-s20120604/snap.txt)
EOF
cd rust-s20120607
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
