#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120323-1 \
    6374ffc5f36da5959d6752e5b15543bb4e00c7a9
git -C rust-s20120323-1 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120323-1/src/libuv
mkdir rust-s20120323-1/dl
cp rust-s20120320/$(< rust-s20120320/snap.txt) rust-s20120323-1/dl
cat > rust-s20120323-1/src/snapshots.txt <<EOF
S 2012-03-20 8404ea0
  linux-x86_64 $(cut -c 45-84 rust-s20120320/snap.txt)
EOF
cd rust-s20120323-1
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -235 +235 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
