#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20121007 \
    d301dd3686ddd04845c1e9f5b9254aa3498a8a7b
git -C rust-s20121007 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20121007/src/libuv
install -Dt rust-s20121007/dl rust-s20121005/$(< rust-s20121005/snap.txt)
cat > rust-s20121007/src/snapshots.txt <<EOF
S 2012-10-05 $(cut -f 6 -d - rust-s20121005/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20121005/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20121007
patch -p1 <<EOF
--- a/configure
+++ b/configure
@@ -432 +432 @@
-	(3.1svn|3.1|3.0svn|3.0)
+	(3.2svn|3.1svn|3.1|3.0svn|3.0)
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -245 +245 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -657 +657 @@
-    explicit ptr(uint8_t *in_p) : p(in_p) {}
+    ptr(uint8_t *in_p) : p(in_p) {}
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc
printf '\a'
