#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20110526 \
    9491dc3e61b114eda06a61bbec76742237017f49
git -C rust-s20110526 config --worktree core.abbrev 7
mkdir rust-s20110526/dl
cp rust-s20110521/$(< rust-s20110521/snap.txt) rust-s20110526/dl
cat > rust-s20110526/src/snapshots.txt <<EOF
S 2011-05-21 $(cut -f 6 -d - rust-s20110521/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20110521/snap.txt | cut -f 1 -d .)
EOF
patch -d rust-s20110526 -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -147 +147 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -d rust-s20110526 -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -88 +88 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
(cd rust-s20110526
PATH="$base"/llvm-3.0svn-2/Release+Asserts/bin:"$PATH" ./configure --disable-docs)
make -C rust-s20110526 -j8 stage2/rustc
(cd rust-s20110526; CFG_SRC_DIR=. src/etc/make-snapshot.py stage2 > snap.txt)
printf '\a'
