#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111031 \
    bd33951b1c59fe968e625fc7379ce2761ede777e
git -C rust-s20111031 config --worktree core.abbrev 7
mkdir rust-s20111031/dl
cp rust-s20111028/$(< rust-s20111028/snap.txt) rust-s20111031/dl
cat > rust-s20111031/src/snapshots.txt <<EOF
S 2011-10-28 3397fa4
  linux-i386 $(cut -c 43-82 rust-s20111028/snap.txt)
EOF
cd rust-s20111031
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -182 +182 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.1svn-1/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
