#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120515 \
    17d6b09d14c916497a6679363308cb7822c4aafe
git -C rust-s20120515 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120515/src/libuv
mkdir rust-s20120515/dl
cp rust-s20120427/$(< rust-s20120427/snap.txt) rust-s20120515/dl
cat > rust-s20120515/src/snapshots.txt <<EOF
S 2012-04-27 $(cut -f 6 -d - rust-s20120427/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120427/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120515
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
