#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20140120 \
    b6400f998497c3958f40997a71756ead344a776d
cd rust-s20140120
git config --worktree core.abbrev 7
git -C "$base"/libuv archive v0.11.19 | tar -xf - -C src/libuv
git -C "$base"/gyp archive master | tar -xf - -C src/gyp
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -153 +153 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
patch -p1 <<EOF
--- a/src/libuv/gyp_uv.py
+++ b/src/libuv/gyp_uv.py
@@ -34 +34 @@
-  proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
+  proc = subprocess.Popen(CC.split() + ['-dumpfullversion'], stdout=subprocess.PIPE)
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20140114/x86_64-unknown-linux-gnu/stage2 \
    --llvm-root="$base"/llvm-3.4svn-1/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
