#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111117-2 \
    dd275cd749fb33e272004cd946eff18ec4d10281
git -C rust-s20111117-2 config --worktree core.abbrev 7
git -C libuv archive node-v0.6.21 | tar -xf - -C rust-s20111117-2/src/libuv
mkdir rust-s20111117-2/dl
cp rust-s20111117-1/$(< rust-s20111117-1/snap.txt) rust-s20111117-2/dl
cat > rust-s20111117-2/src/snapshots.txt <<EOF
S 2011-11-17 $(cut -f 6 -d - rust-s20111117-1/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20111117-1/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20111117-2
patch -p1 <<'EOF'
--- a/configure
+++ b/configure
@@ -413 +413 @@
-if [ $NEED_INIT ]
+if false
@@ -419 +419 @@
-if [ $NEED_UPDATE ]
+if false
EOF
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -204 +204 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -100,0 +101 @@
+#define alignof rust_alignof
@@ -883 +884 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
./configure --disable-docs --llvm-root="$base"/llvm-3.1svn-1/Release+Asserts
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
