#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-t20110727 \
    f45524d0d4831f4951f311d9a8603afd78b13dc1
git -C rust-t20110727 config --worktree core.abbrev 7
mkdir rust-t20110727/dl
cp rust-s20110721/$(< rust-s20110721/snap.txt) rust-t20110727/dl
cat > rust-t20110727/src/snapshots.txt <<EOF
S 2011-07-21 c62a9fe
  linux-i386 $(cut -c 43-82 rust-s20110721/snap.txt)
EOF
cd rust-t20110727
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -151 +151 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -fno-exceptions -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -fno-exceptions -g
EOF
patch -p1 <<'EOF'
--- a/mk/rt.mk
+++ b/mk/rt.mk
@@ -97 +97 @@
-	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS),$(RUNTIME_DEF))
+	$(Q)$(call CFG_LINK_C,$@,$(RUNTIME_LIBS) $(RUNTIME_OBJS) -lpthread,$(RUNTIME_DEF))
EOF
patch -p1 <<EOF
--- a/src/comp/driver/rustc.rs
+++ b/src/comp/driver/rustc.rs
@@ -538 +538 @@
-        [stage, "-Lrt", "-lrustrt", glu,  "-m32", "-o",
+        [stage, glu,  "-m32", "-o",
@@ -601,0 +602 @@
+    gcc_args += ["-Lrt", "-lrustrt"];
EOF
patch -p1 <<EOF
--- a/src/rt/rust_util.h
+++ b/src/rt/rust_util.h
@@ -210 +210 @@
-    uint8_t data[];         // if on stack
+    uint8_t data[0];        // if on stack
EOF
PATH="$base"/llvm-3.0svn-5/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage1
echo rust-stage0* > snap.txt
printf '\a'
