#!/bin/bash
mkdir llvm-3.0svn-6
git -C llvm-project archive d3e65e702f45ea3476f3bda2b8f69a3e3729e9e2 llvm |
tar -xf - -C llvm-3.0svn-6 --strip-components=1
cd llvm-3.0svn-6
patch -p1 <<EOF
--- a/include/llvm/ADT/IntervalMap.h
+++ b/include/llvm/ADT/IntervalMap.h
@@ -1980 +1980 @@
-    Node[NewNode] = this->map->newNode<NodeT>();
+    Node[NewNode] = this->map->template newNode<NodeT>();
--- a/include/llvm/ADT/PointerUnion.h
+++ b/include/llvm/ADT/PointerUnion.h
@@ -266 +266 @@
-      return Ty(Val).is<T>();
+      return Ty(Val).template is<T>();
@@ -279 +279 @@
-      return Ty(Val).get<T>();
+      return Ty(Val).template get<T>();
--- a/tools/bugpoint/ToolRunner.cpp
+++ b/tools/bugpoint/ToolRunner.cpp
@@ -131 +131 @@
-    errs() << OS;
+    errs() << OS.str();
EOF
./configure --build=i686-unknown-linux-gnu --disable-jit --disable-docs \
    --disable-threads --disable-pthreads --enable-targets=x86 \
    --enable-bindings=none
make -j8 CC='gcc -m32' CXX='g++ -m32'
printf '\a'
