#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120310 \
    98260a2a22ab693f2363c68339cf5bb9fca011ab
git -C rust-s20120310 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120310/src/libuv
mkdir rust-s20120310/dl
cp rust-s20120305/$(< rust-s20120305/snap.txt) rust-s20120310/dl
cat > rust-s20120310/src/snapshots.txt <<EOF
S 2012-03-05 $(cut -f 6 -d - rust-s20120305/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120305/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120310
git diff 205cefdc6e0e53c6df8075b5c37edd4e0803a598^! | git apply
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -239 +239 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -6,0 +7 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -108,0 +109 @@
+#define alignof rust_alignof
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
