#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20111023 \
    ff669cf5ad38097970fe026e19f8a39f8d7b4e18
git -C rust-s20111023 config --worktree core.abbrev 7
mkdir rust-s20111023/dl
cp rust-s20111021/$(< rust-s20111021/snap.txt) rust-s20111023/dl
cat > rust-s20111023/src/snapshots.txt <<EOF
S 2011-10-21 $(cut -f 6 -d - rust-s20111021/snap.txt)
  linux-i386 $(cut -f 9 -d - rust-s20111021/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20111023
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -182 +182 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
patch -p1 <<EOF
--- a/src/rt/rust_cc.cpp
+++ b/src/rt/rust_cc.cpp
@@ -7,0 +8 @@
+#undef alignof
EOF
patch -p1 <<EOF
--- a/src/rt/rust_shape.h
+++ b/src/rt/rust_shape.h
@@ -97,0 +98 @@
+#define alignof rust_alignof
@@ -880 +881 @@
-    void walk_number() { DATA_SIMPLE(W, walk_number<W>()); }
+    void walk_number() { DATA_SIMPLE(W, template walk_number<W>()); }
EOF
PATH="$base"/llvm-3.1svn-1/Release+Asserts/bin:"$PATH" ./configure --disable-docs
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
