#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20130328 \
    f7a2371c176663d59062ec5158f39faecba45768
git -C rust-s20130328 config --worktree core.abbrev 7
git -C libuv archive v0.11.5 | tar -xf - -C rust-s20130328/src/libuv
cd rust-s20130328
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -124 +124 @@
-CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -Werror -g -fPIC -m64
+CFG_GCCISH_CFLAGS_x86_64-unknown-linux-gnu := -Wall -g -fPIC -m64
EOF
./configure --disable-docs --disable-manage-submodules --enable-local-rust \
    --local-rust-root="$base"/rust-s20130327/x86_64-unknown-linux-gnu/stage1 \
    --llvm-root="$base"/llvm-3.2svn-1/Release+Asserts
make -j8 rustc-stage1
printf '\a'
