#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120524 \
    433e4ca5f166f2e3322b90bc53f32bc44d534640
git -C rust-s20120524 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120524/src/libuv
mkdir rust-s20120524/dl
cp rust-s20120515/$(< rust-s20120515/snap.txt) rust-s20120524/dl
cat > rust-s20120524/src/snapshots.txt <<EOF
S 2012-05-15 17d6b09
  linux-x86_64 $(cut -c 45-84 rust-s20120515/snap.txt)
EOF
cd rust-s20120524
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
