#!/bin/bash
base=$(pwd)
git -C rust worktree add "$base"/rust-s20120604 \
    7213274e57ef779620e6d68939816c66201d7d36
git -C rust-s20120604 config --worktree core.abbrev 7
git -C libuv archive node-v0.7.5 | tar -xf - -C rust-s20120604/src/libuv
install -Dt rust-s20120604/dl rust-s20120602/$(< rust-s20120602/snap.txt)
cat > rust-s20120604/src/snapshots.txt <<EOF
S 2012-06-02 $(cut -f 6 -d - rust-s20120602/snap.txt)
  linux-x86_64 $(cut -f 9 -d - rust-s20120602/snap.txt | cut -f 1 -d .)
EOF
cd rust-s20120604
patch -p1 <<EOF
--- a/mk/platform.mk
+++ b/mk/platform.mk
@@ -246 +246 @@
-  CFG_GCCISH_CFLAGS += -Wall -Werror -fno-rtti -g
+  CFG_GCCISH_CFLAGS += -Wall -fno-rtti -g
EOF
./configure --disable-docs --disable-manage-submodules \
    --llvm-root="$base"/llvm-3.1svn-4/Release+Asserts
make -j8 snap-stage2
echo rust-stage0* > snap.txt
printf '\a'
